// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomReservation.Infrastructure.Context;

#nullable disable

namespace RoomReservation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250504183515_reservationSeed")]
    partial class reservationSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomReservation.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Projektor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tablica"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zestaw do wideokonferencji"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ekran"
                        });
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 6, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            StartDate = new DateTime(2025, 6, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            StartDate = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2025, 6, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            StartDate = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2025, 6, 7, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            StartDate = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2025, 6, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            StartDate = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("RoomLayout")
                        .HasColumnType("int");

                    b.Property<int>("TableCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Name = "Klasa",
                            RoomLayout = 2,
                            TableCount = 20
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            Name = "Sala konferencyjna 5",
                            RoomLayout = 0,
                            TableCount = 4
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            Name = "Scena",
                            RoomLayout = 1,
                            TableCount = 0
                        });
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.RoomEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomsEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            Quantity = 2,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 2,
                            Quantity = 0,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 3,
                            Quantity = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 4,
                            Quantity = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 1,
                            Quantity = 3,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 3,
                            Quantity = 4,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 7,
                            EquipmentId = 2,
                            Quantity = 1,
                            RoomId = 3
                        });
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.RoomReservationLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxTime")
                        .HasColumnType("int");

                    b.Property<int?>("MinTime")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomsReservationLimits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxTime = 90,
                            MinTime = 30,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            MaxTime = 0,
                            MinTime = 0,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            MaxTime = 60,
                            MinTime = 0,
                            RoomId = 3
                        });
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "IdioP+/nL+5jf8yWL3tVYWMa5g6sgNIs5w4JFQNXuEs=",
                            Username = "jnowak"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Ix7MfReNpfIpg7xXlZk5bWwTmkV5h64e4AJtiEMtanI=",
                            Username = "kkowalski"
                        },
                        new
                        {
                            Id = 3,
                            Password = "VOoS58R1AHocCK0wA764P3UC5yn2xjOL5ZfEggL9MAU=",
                            Username = "unowakowski"
                        });
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("RoomReservation.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomReservation.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.RoomEquipment", b =>
                {
                    b.HasOne("RoomReservation.Domain.Entities.Equipment", "Equipment")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomReservation.Domain.Entities.Room", "Room")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.RoomReservationLimit", b =>
                {
                    b.HasOne("RoomReservation.Domain.Entities.Room", "Room")
                        .WithOne("RoomReservationLimit")
                        .HasForeignKey("RoomReservation.Domain.Entities.RoomReservationLimit", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.Room", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("RoomEquipments");

                    b.Navigation("RoomReservationLimit");
                });

            modelBuilder.Entity("RoomReservation.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
